### ISSUE TITLE
License for NS

### ISSUE THREAD

**Issue by sparticvs** [popebp/neat-sheets#3]
Do we wish to use a commercial permissive license like BSD Clause 2 or MIT, or do we want something like GPLv2 or Apache where no commercial alternatives are permitted? Then there is the question if we want to restrict commercial alternatives, by using a viral license like GPL?

**Comment by dewees** [comment]
I'm in favor of a commercial permissive license

**Comment by sparticvs** [comment]
I think MIT is the most permissive, so I am cool with that if you are.

**Comment by sparticvs** [comment]
Done.
